src/modules/AmidoBuild/exported/Build-DockerImage.Tests.ps1, src/modules/AmidoBuild/exported/Build-DockerImage.ps1, src/modules/AmidoBuild/exported/Publish-GitHubRelease.Tests.ps1, src/modules/AmidoBuild/exported/Publish-GitHubRelease.ps1, taskctl.yaml
Please note: intermediate fix was required for the centralisation of TaskCTL tasks, so the branch name is not accurate.
📲 What
Adds support for generic Docker Registries
Fixes Broken Publish-GitHubRelease tests
🤔 Why
Generic docker registries as required to support the build and publish the images used by the independent runner.
Broken tests for Publish-GitHubRelease
🛠 How
Standard PS function implementation.
👀 Evidence
Locally, the Build-DockerImage command is run and has deployed to a generic registry, https://hub.docker.com/repository/docker/williamamido/runner-pwsh while tests continue to succeed.
Publish-GitHubRelease tests now run 100% : https://amido-dev.visualstudio.com/Amido-Stacks/_TestManagement/Runs?runId=1112474&_a=runCharts
🕵️ How to test
The following command will succeed …
=> Adds support for generic Docker Registries, Fixes Broken Publish-GitHubRelease tests

src/modules/AmidoBuild/exported/Build-DockerImage.ps1
Splits azurecr.io suffix from ACR-based registry pushes
To ensure support of multiple container registries, the safer bet is to amend the variable used to include the suffix, and have it split conditionally when an ACR is specified.
Standard PS.
Link to [builds](https://dev.azure.com/amido-dev/Amido-Stacks/_build/results?buildId=20667&view=results)
Notes for QA
=> BUGFIX : Rewrites registry value for ACR login.

build/azuredevops-runner.yml, src/modules/AmidoBuild/command/Invoke-External.ps1, src/modules/AmidoBuild/exported/Build-DockerImage.Tests.ps1, src/modules/AmidoBuild/exported/Build-DockerImage.ps1
Updated the `Build-DockerImage` cmdlet so that the name and tag are changed to lower case when called by Docker.
Output the command being called to the console during the build.
Docker does not allow names of images or the tags to be anything other than lowercase.
It is hard to debug issues in the pipeline when the command that has been executed cannot be checked.
For the name and the tag a simple lowercase conversion is being perfomed in the function. The tests have been updated to test for this evntuallity.
A simple `Write-Information` call has been added to the `Invoke-External` command when a command is about to be executed, e.g. not in dry-run. This will output the command to the log.
=> Fix issue when ceating a Docker image

build/azuredevops-runner.yml, build/taskctl/contexts.yaml
Added quotes to the values in the envvar file
In the `envfile` created for the context the values of the variables are not quoted which means that values that have spaces can and will cause Docker to throw an error.
Added an `awk` command to the command pipeline so that all values are quoted in the file.
The values in the file are now properly quoted
=> Fix value of environment variables going into Docker

src/modules/AmidoBuild/command/Invoke-External.ps1
Corrected the parameter name for `Write-Information`
The parameter had been misspelled and caused the cmdlet to break
Corrected the name
Tests are now running and passing.
We need to make sure that failed tests fail the build
=> Corrected parameter name

src/modules/AmidoBuild/cloud/Connect-EKS.Tests.ps1, src/modules/AmidoBuild/cloud/Connect-EKS.ps1, src/modules/AmidoBuild/exported/Build-DockerImage.Tests.ps1, src/modules/AmidoBuild/exported/Build-DockerImage.ps1, src/modules/AmidoBuild/exported/Invoke-Login.Tests.ps1, src/modules/AmidoBuild/exported/Invoke-Login.ps1
Extended `Invoke-Login` to support validation of AWS login credentials, and calling `connect-eks`.
Implemented `connect-eks` as separate cmdlet.
AWS is strategic objective of this work.
`connect-eks` is required as a separate cmdlet despite being a one-liner calling `invoke-external`, in order that it can be both mocked during tests and be wrapped by the flag `-dryrun` which is supported by `invoke-login`. 
Standard Module usage.
Invoke-Login for AWS (without Connect-EKS):
```
> $DebugPreference = "Continue"
> invoke-login -aws            
DEBUG: AWS env vars for AWS_ACCESS_KEY_ID=<omitted> , and AWS_SECRET_ACCESS_KEY (not shown) and AWS_DEFAULT_REGION=eu-west-2 found OK
```
Connect-EKS:
```
> $DebugPreference = "Continue"
> . Connect-EKS.ps1
> Connect-EKS -name <omitted> -region …
```
=> Permits ECR image push and EKS deployment

src/modules/AmidoBuild/exported/Build-DockerImage.Tests.ps1, src/modules/AmidoBuild/exported/Build-DockerImage.ps1
Removed quotes around `buildArgs` that are passed to `docker` in the `Build-DockerImage` cmdlet
When values are passed to the module in Azure DevOps they can be surrounded by literal quotes which makes the docker command invalid, e.g.:
`docker build "--build-arg functionName=PesterFunction ." -t pester-tests:unittests -t pesterreg/pester-tests:unittests -t pesterreg/pester-tests:latest`
There should be no quotes in the command, docker will return an error stating that exactly one argument should be passed.
Have added a trim to the `$buildArgs` variable so that if it contains a strinig with surrounding quotes they will be removed. This will not affect quotes within the string.
Tests have been added to check that the quotes are removed correctly
When running in ADO with a test Docker image …
=> Removed start and end quotes from buildArgs when passed to Docker

src/modules/AmidoBuild/exported/Invoke-Terraform.Tests.ps1, src/modules/AmidoBuild/exported/Invoke-Terraform.ps1
Allowed all of the options to be passed to the `backend` parameter of `Invoke-Terraform` in the first item of the array. If this is the case then the method will attempt to split the strng using the `,` character so that the options can be split up as required by Terraform.
An array can still be passed to the method.
Any backed configurations that need to be passed to Terraform init as multiple `-backend-config` switches.
This was catered for if the `backend` parameter to `Invoke-Terraform` was passed as an arry but not if it was passed as a comma delimited string which can be the case on the command lline and definitely the case when using enviornment variables.
The Backend configuration can now be specified as trhe `TF_BACKEND` environment variable.
If the method sees that the internal …
=> Update Invoke-Terraform to handle single backend string

src/modules/AmidoBuild/exported/Invoke-Terraform.Tests.ps1, src/modules/AmidoBuild/exported/Invoke-Terraform.ps1
Moved where the arguments are split on the delimiter.
Also checking in the missing code that allows the sdelimiter for the split to be modified.
Updated tests to check that the split works for all situations
In a previous PR the arguments were being split but only for the `init` parameter set. Arguments are also used for the `plan` parameter for example. The splitting of the arguments is now done for all the subcommands.
An update to allow the delimiter to be changed had been missed off the previos PR.
If an argument string is detected, e.g. there is just one element to the array then it will be split using the delimiter character (which defaults to ",") at the start of the function, before the selection of the command is performed.
This now means that all commands can be beneift from …
=> Moved where splitting out arguments is performed

.gitignore, build/azuredevops-runner.yml, build/azuredevops-vars.yml, build/scripts/Build-Help.ps1, build/scripts/Invoke-PesterTests.ps1, build/taskctl/contexts.yaml, build/taskctl/tasks.yaml, docs/cmdref.adoc, docs/index.adoc, docs/notes.adoc, docs/usage/usage.adoc, src/modules/AmidoBuild/AmidoBuild.psd1, src/modules/AmidoBuild/command/Invoke-External.Tests.ps1, src/modules/AmidoBuild/command/Invoke-External.ps1, src/modules/AmidoBuild/command/Stop-Task.Tests.ps1, src/modules/AmidoBuild/command/Stop-Task.ps1, src/modules/AmidoBuild/exported/Confirm-Environment.Tests.ps1, src/modules/AmidoBuild/exported/Confirm-Environment.ps1, src/modules/AmidoBuild/exported/Invoke-Terraform.Tests.ps1, src/modules/AmidoBuild/exported/Invoke-Terraform.ps1
Fixed issue with the tests coverage being completed successfully.
Added `Confirm-Environment` that checks all the required environment variables have been set, according to a settings file in the repository.
Added `Stop-Task` which throws an exception which makes `taskctl` break out of the pipeline
Updated documentaion
The task for running the Unit test coverage was failing due to the output of Pester including characters that look like Golang templating
A lot of the configuration in the independent runner can be set using enviornment variables, however it is not obvious what these need to be. The new `Confirm-Environment` cmdlet performs this task and fails when env vars are missing and states which ones need to be set.
When tasks were failing previously, `taskctl` did not break out of …
=> Added new cmdlets which check the build environment and stop tasks in the event of an error

build/azuredevops-runner.yml, build/config/stage_envvars.yml, build/taskctl/contexts.yaml, build/taskctl/tasks.yaml, src/modules/AmidoBuild/exported/Confirm-Environment.ps1, taskctl.yaml
Added a new task in the pipeline called `setup:environment` which calls the `Confirm-Environment` PowerShell function to ensure all the enviornment variables exist for the successful running of the pipeline
After the last PR the release stage ran but there was no release on GitHub.
By adding the `Confirm-Environment` is it possible now to check that all the required enviornment variables exist to allow the task to complete.
Modified the `context.yaml` file so that the module itself is picked up, this means that the latest version is being used when performing the build.
Added  a new file `stage_envvars.yml` to the repo to ensure that the `Confirm-Enviornment` function has the necessary config to determine which vars should exist.
When the guard for running a release on a branch was …
=> Enabled `Confirm-Environment` check for GitHub release

src/modules/AmidoBuild/exported/Invoke-Asciidoc.Tests.ps1, src/modules/AmidoBuild/exported/Invoke-Asciidoc.ps1
Allow environment variables to be used in AsciiDoc attribute substituions
A lot of the documentation that is generated in Stacks has references to the version number that has been built. However the value for BUILDNUMBER has not be substituted in and the default of `100.98.99` is being used.
By adding all environment variables to the tokens hashtable in the `Invoke-AsciiDoc` cmdlet it is possible to allow any substitution as an attribuite.
The `Invoke-AsciiDoc` cmdlet has a tokens hashtable that already contained the format and basepath.
This has now been augmented so that all environment variables are added to the table.
Unittests have been updated to include a substitution at the attribute level.
Notes for QA
=> Updated AsciiDoc substitutions to include all environment vars

src/modules/AmidoBuild/exported/Invoke-Terraform.ps1
Adds `-or-create` flag to workspace selection command
Do not need to error check for failed workspace selection commands
Update PS
```
PS /Users/williamayerst/Repos/Stacks/independent-runner> invoke-terraform -Workspace -Arguments bacon                 
Tool found: /opt/homebrew/bin/terraform
Working directory: /Users/williamayerst/Repos/Stacks/independent-runner
Attempting to select or create workspace: bacon
terraform workspace select -or-create=true bacon
Created and switched to workspace "bacon"!
You're now on a new, empty workspace. Workspaces isolate their state,
so if you run "terraform plan" Terraform will not see any existing state
for this configuration.
PS /Users/williamayerst/Repos/Stacks/independent-runner> 
```
Notes for QA
=> Updates Workspace Command

.gitignore, build/azuredevops-runner.yml, build/scripts/Invoke-PesterTests.ps1, build/scripts/Test-PesterExitCode.ps1, build/taskctl/contexts.yaml, build/taskctl/tasks.yaml, src/modules/AmidoBuild/exported/Invoke-Helm.Tests.ps1, src/modules/AmidoBuild/exported/Invoke-Helm.ps1, src/modules/AmidoBuild/exported/Invoke-Inspec.Tests.ps1, src/modules/AmidoBuild/exported/Invoke-Inspec.ps1, src/modules/AmidoBuild/exported/Invoke-Terraform.Tests.ps1, src/modules/AmidoBuild/exported/Invoke-Terraform.ps1, src/modules/AmidoBuild/exported/Invoke-YamlLint.Tests.ps1, taskctl.yaml
fix: Fixes build false passing by handling errors
* Gracefully handles Pester errors by storing the exit code in a file, running the next code coverage task, and then finally running a task which will exit based on the exit code in the file. This should make the build fail now, while still running the HTML Code Coverage generation task.
* Fixes the YAMLLint test, leaving TF deliberately failing to see if the build now fails as expected.
* Ensures the build runs the root `tests` task and not the individual
ones.
feat: Adds `repo` command to Helm
* Adds a `-Repo` command for adding repos to Helm, this means it's no
longer required to use a custom command
* The new `-Repo` command doesn't log into a Cloud Provider
whereas `-Custom` still does (to maintian bc)
* Fixes the Helm tests which …
=> feat: Adds `-Repo` command to Helm

src/modules/AmidoBuild/command/Invoke-External.ps1
Provide realtime feedback of Invoke-External commands
Without this you have to wait until the command has finished before you see the output.
Now when running a command e.g. terraform apply, you can see the progress. 
Removed the code that puts the output of Invoke-External into a variable
=> Provide realtime feedback of Invoke-External commands

src/modules/AmidoBuild/exported/Invoke-YamlLint.ps1
In order for YAMLLint ignore paths to work, pass in `.` as the default path instead of `(Get-Location)`.
=> fix: Changes base path for yamllint to `.`

src/modules/EnsonoBuild/exported/Build-DockerImage.Tests.ps1, src/modules/EnsonoBuild/exported/Build-DockerImage.ps1
Corrected the `Build-DockerImage` cmdlet so that when a custom registry is specified it does *not* just tag without a registry.
Fixes #45
When a registry was not specified, the new image was tagged without one. So this meant that when the image was pushed using `docker push` it will go to docker.io.
However when a custom registry is specified the image was tagged with the correct custom registry as well as without one. This meant that when the cmdlet tried to push the image it would attempt to push to the custom registry as well as docker.io.
This has been fixed as such:
1. When no registry is specified, it is automatically set as `docker.io`. This means that there is no chance the image is named without a registry
2. The default value for the `buildArgs` was `.` which meant that Docker …
=> Update module cmdlet to correctly create Docker Image

src/modules/EnsonoBuild/command/Invoke-External.ps1, src/modules/EnsonoBuild/exported/Invoke-Terraform.Tests.ps1, src/modules/EnsonoBuild/exported/Invoke-Terraform.ps1
The changes to the `Invoke-Terraform` cmdlet allow the version of Terraform to be chosen.
With Terraform versions being released on a regular basis it is hard to keep everything in line. The https://github.com/Ensono/stacks-docker-images now allow multiple versions of Terraform to be installed - https://github.com/Ensono/stacks-docker-images/pull/99.
A symlink is created in the docker image to the version that is going to be used by default. This is added to the PATH in the image. For example:
`/usr/local/terraform/1.5.1/bin -> /usr/local/terraform/bin`
This is very useful to have a quick way to run TF when running in the container interactively, but when using `Invoke-Terraform` we need a way to be able to specify the version.
Two new parameters have been added to the cmdlet:
__Prefix__ …
=> Select version of Terraform to use

src/modules/EnsonoBuild/exported/Invoke-Terraform.Tests.ps1, src/modules/EnsonoBuild/exported/Invoke-Terraform.ps1
Sets TF output depth to 50, customisable
The default depth of 2 is no good if you have a heavily nested JSON output from Terraform
Allows a depth to be set and sets a high 50 depth instead of the default 2
See tests
`taskctl tests`
=> fix: Sets TF output depth to 50, customisable

build/azuredevops-runner.yml, build/taskctl/tasks.yaml, build/templates/setup.yaml, src/modules/EnsonoBuild/exported/Publish-GitHubRelease.Tests.ps1, src/modules/EnsonoBuild/exported/Publish-GitHubRelease.ps1, src/modules/EnsonoBuild/exported/Update-InfluxDashboard.ps1, taskctl.yaml
Fixes GH Release to error if artefacts don't exist and fail. Adds the functionality and tests surrounding this, plus adds a test for existing behaviour not covered (failure to upload an artefact).
If artefacts didn't exist it'd carry on regardless which isn't what we want. This doesn't stop if no artefacts are specified, i.e. it doesn't fail if there's no filter but an artefacts dir is specified.
Published release without Artefacts and didn't fail:
New behaviour fails if files can't be found:
Published Artefacts:
=> feat: fixes GH Publish to crash if files not found

src/modules/EnsonoBuild/exported/Invoke-SonarScanner.Tests.ps1, src/modules/EnsonoBuild/exported/Invoke-SonarScanner.ps1
`sonar.login` is deprecated, use `sonar.token` instead.
What have you implemented?
`sonar.login` is deprecated and issues warnings in SonarCloud.
=> fix: sonar.login is deprecated, use sonar.token

src/modules/EnsonoBuild/EnsonoBuild.psd1, src/modules/EnsonoBuild/exported/Invoke-Asciidoc.ps1
Added `Invoke-Extnernal` and `Stop-Task` to the PSD1 file so that they are exported when the module is loaded.
Added `ExitCodes` as an argument to `Invoke-AsciiDoc` so they can be passed to `Invoke-External` to ignore certain ones.
Although the cmdlets were in the `exported` folder this does not export them by default. The module data file needs to be updated with the cmdlet. This is done automatically with a formal build. but if running locally they will not be exported.
Need to be able to permit extra exit codes when running `Invoke-AsciiDoc`
Added the two cmdlets to the `FunctionsToExport` list in the `EnsonoBuild.psd1` file.
Created a new parameter for `Invoke-AsciiDoc` to accept additional exit codes and then pass that as `AdditionalExitcodes` to `Invoke-External`.
Link to …
=> Update list of exported commands and allowed additional exitcodes on a cmdlet

build/taskctl/tasks.yaml
Removes `exportAs` as it's not being used we think, and it's no longer in `taskctl`.
To fix the local builds
Notes for QA
=> fix: removes exportAs key

build/config/stage_envvars.yml, build/taskctl/contexts.yaml, build/taskctl/tasks.yaml, src/modules/EnsonoBuild/exported/Build-PowerShellModule.ps1
Passes in the version to the module generation
Currently the module always shows `0.1` as the version which isn't helpful for debugging the installed version.
=> fix: version passed in correctly to module gen
